# Generated by Django 3.0.5 on 2020-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0003_auto_20200405_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='gatunek',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
